### ISSUE TITLE
Proxy Server with cURL Object

### ISSUE THREAD

**Issue by James-Hogan** [ropensci/clifro#5] opened 2016-11-22 03:50 UTC
Hi Contributors,

I'm using this code in MBIE's IT environment, and its failing because of our proxy server.  Normally, we initialise a cURL object :

```
creds <- AskCreds(Title = "User Log In Name and Password", startuid = "", returnValOnCancel = "ID_CANCEL")   
curl <- getCurlHandle()
curlSetOpt(.opts = list(proxy = 'http://xxxxx.yyyy.govt.nz:8080',
                        proxyusername  = creds$uid, 
                        proxypassword  = creds$pwd,
                        ssl.verifypeer = FALSE), curl = curl)   
```
but all throughout the code, cURL objects are being derived within the functions, and overwriting the proxy settings needed to query outside our firewire.  

I was wondering whether it the code can be refactored to remove the cURL option setting happening within different places, so the proxy settings can be established before the Clifro functions are called?  Forking the project and refactoring an R library is a little bit beyond my experience.

Cheers,
James Hogan

**Comment by blasee** [comment] 2016-11-30 01:04
Hi James,

Thanks for submitting the issue. I've just pushed a development version of clifro to the iss05 branch. Would you mind installing the package from this branch and let me know how you go? The following is some code to get you started:

```r
devtools::install_github("ropensci/clifro", ref = "iss05")
library(clifro)

# Set global curl options that are used for all clifro queries
cf_curl_opts(.opts = list(proxy = 'http://xxxxx.yyyy.govt.nz:8080',
                        proxyusername  = creds$uid, 
                        proxypassword  = creds$pwd,
                        ssl.verifypeer = FALSE))
```
These options will now be passed to all curl handles initiated in clifro. 

Let me know how this goes, and any suggestions are welcomed.

Thanks,
Blake

**Comment by James-Hogan** [comment] 2016-11-30 03:42
Hi Blake,

Thank you very much!  Adapting your code is very kind.

I’ll let you know  how it goes :)

Best regards,
James

James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140

**Comment by blasee** [comment] 2016-12-20 09:33
Closing issue as I suspect this has been adequately addressed in the latest CRAN release (3.1).

**Comment by James-Hogan** [comment] 2016-12-20 20:22
Thank you Blake.  We’re upgrading our version of R and include your Clifro modification when we refresh the libraries ☺



James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140

**Comment by blasee** [comment] 2016-12-20 22:05
I'll happily reopen if you run into problems :-)

**Comment by James-Hogan** [comment] 2016-12-22 01:21
Hi Blake,

You might have closed the issue too soon.  Here’s what we’re finding when we test the latest Clifro package in our system.

Any ideas for what’s happening?


Cheers,
James

James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140

**Comment by James-Hogan** [comment] 2017-01-08 23:39
Thanks Blake :D

James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140

**Comment by blasee** [comment] 2017-01-09 00:02
Hi James,

It's a little hard for me to diagnose this issue without a reproducible example. Could you please send the output of `sessionInfo()`. Also, may I suggest that you update your version of R (your version is over 2 years old), and also download the latest dev version of `clifro` (3.1-999) I've just pushed to GitHub. Let me know how you go.

Thanks,
Blake

**Comment by James-Hogan** [comment] 2017-01-09 00:05
Hi Blake,

I’ll hand this email over to Eric Wu.  Eric’s been adapting the clifro library to our IT system.  Eric will be able to provide the information you need.

Thanks for helping us with this – we appreciate it :)

Cheers,
James




James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140

**Comment by blasee** [comment] 2017-01-09 00:08
No worries!

**Comment by HaizhenWu** [comment] 2017-01-09 00:10
Hi Blake,

I haven't seen your comments on the other issue, which is related to this one. 

I could merge this issue to it and close this one. 

Eric

**Comment by blasee** [comment] 2017-01-09 00:14
Duplicate of issue #7

**Closed by blasee** 2017-01-09 00:14 UTC

**Comment by James-Hogan** [comment] 2017-01-09 00:25
Hi All,

Blake has updated the dev version (clifro_3.1-999). I have installed to our system and get it tested.

This version works well.

[cid:image001.png@01D26A7B.CFC17710]

Kind regards,
Eric

From: James Hogan
Sent: Monday, 9 January 2017 1:05 p.m.
To: ropensci/clifro
Cc: Eric Wu; Peter Ellis (Wellington)
Subject: FW: [ropensci/clifro] Proxy Server with cURL Object (#5) [UNCLASSIFIED]

Hi Blake,

I’ll hand this email over to Eric Wu.  Eric’s been adapting the clifro library to our IT system.  Eric will be able to provide the information you need.

Thanks for helping us with this – we appreciate it :)

Cheers,
James




James Hogan
MANAGER

Energy and Building Trends; Evidence, Monitoring and Governance;  Corporate, Governance and Information
Ministry of Business, Innovation & Employment

James.Hogan@mbie.govt.nz<mailto:James.Hogan@mbie.govt.nz> | Telephone: +64 4 901 1691 | Mobile: +64 275 997 999
15 Stout Street, PO Box 1473, Wellington 6140
